In [4]:
import numpy as np

In [5]:
def QR(A):
    N = len(A[0])
    U = np.zeros([N,N])
    Q = np.zeros([N,N])
    R = np.zeros([N,N])
    U[0] = A[0]
    Q[0] = U[0] / np.linalg.norm([U[0]])
    for i in range(1,N):
        s = np.zeros(N)
        for j in range(i+1):
            s = s + ( np.dot(Q[j],A[i]) * Q[j] )
        U[i] = A[i] - s
        Q[i] = U[i] / np.linalg.norm(U[i])
    for k in range(N):
        R[k,k] = np.linalg.norm(U[k])
        for l in range(k+1,N):
            R[k,l] = np.dot(Q[k],A[l])
    Q = np.matrix.transpose(Q)
    results = [Q,R]
    return results

A1 = np.array([[1,4,8,4],[4,2,3,7],[8,3,6,9],[4,7,9,2]],float)
x1,V1 = np.linalg.eigh(A1)

In [9]:
def eigen(A,epsilon):
    N = len(A[0])
    V = np.identity(N)
    values = np.zeros(N)
    trigger = True
    while trigger:
        trigger = False
        Q = QR(A)[0]
        R = QR(A)[1]
        A = np.dot(R,Q)
        V = np.dot(V,Q)
        for i in range(N):
            for j in range(N):
                if A[i,j] > epsilon and i!=j :
                    trigger = True
    for i in range(N):
        values[i] = A[i,i]
    return [values,V]


data = eigen(A1,1e-6)
print(data[0])
print(data[1])
# x1 = [-8. -3.  1. 21.]        
print(x1)
print(V1)                    

[ 21.  -8.  -3.   1.]
[[ 0.43151698 -0.38357064 -0.77459666 -0.25819889]
 [ 0.38357063  0.43151698 -0.2581989   0.77459667]
 [ 0.62330228  0.52740965  0.25819889 -0.51639778]
 [ 0.52740965 -0.62330227  0.51639779  0.25819889]]
[ -8.  -3.   1.  21.]
[[-0.38357064 -0.77459667  0.25819889 -0.43151697]
 [ 0.43151697 -0.25819889 -0.77459667 -0.38357064]
 [ 0.52740963  0.25819889  0.51639778 -0.62330229]
 [-0.62330229  0.51639778 -0.25819889 -0.52740963]]
